### ISSUE TITLE
Query type of `snd_seq_query_subscribe_t` is not set before calling `snd_seq_query_port_subscribers()`

### ISSUE THREAD

**Issue by Zero0one1** [drobilla/patchage#1]
According to the [ALSA library document](https://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_subscribe.html#gac9c05af9bb647d1aa9b4408f571c809d) of `snd_seq_query_port_subscribers()`, we need to set the client, port, index, query type of the second parameter `subs`, whose type is `snd_seq_query_subscribe_t`, using corresponding APIs.

> At least, the client id, the port id, the index number and the query type must be set to perform a proper query.

However, `sinfo` in L265 lacks the query type set using `snd_seq_query_subscribe_set_type()`([doc](https://www.alsa-project.org/alsa-doc/alsa-lib/group___seq_subscribe.html#gad78be14f613420a840ef0fc3ebdf3740)).

https://github.com/drobilla/patchage/blob/34f5d891fabe5c4e6137ce3d94aee8ca1955ebab/src/AlsaDriver.cpp#L261-L265

**Comment by drobilla** [comment]
Fixed in 0b413ac, thanks.
